import json,csv,html,copy
from pathlib import Path
from datetime import datetime,timezone
from src.model import load,forecast,value,dump_csv

def save(path,text):Path(path).write_text(text,encoding='utf8')
def run():
 r=json.loads(Path('outputs/results.json').read_text());data,c=load();base=c['cases']['base']
 stresses=[]
 shock=copy.deepcopy(base);shock['commercial_growth']=[0,-.10,.15,.20,.15];shock['government_growth']=[0,.05,.10,.12,.12];shock['margins']=[.46,.25,.30,.34,.35];shock['nwc_ratio']=.12;shock['wacc']=.12
 for name,case in [('Procurement delay and AI deployment failure',shock),('Commercial conversion slowdown',c['cases']['low'])]:
  v=value(forecast(case,data,c),case,data,c);stresses.append(dict(scenario=name,value=v['per_share'],current_action=v['action'],conditional_price=20,conditional_action='do_not_initiate' if 20>v['per_share']*1.2 else 'watch_defer'))
 # Terminal-maturity challenge: continue transition cash flows inside terminal convention.
 # These are explicit terminal-convention calculations, not an inconsistent separate five-year forecast.
 last=forecast(base,data,c)[-1]['revenue'];transition_pv=0;w=base['wacc'];g=base['growth'];roic=c['terminal_roic']
 for t,(growth,margin) in enumerate(zip(c['terminal_fade']['growth'],c['terminal_fade']['margin']),1):
  last*=1+growth;nopat=last*margin*(1-c['tax']);f=nopat*(1-growth/roic);transition_pv+=f/(1+w)**t
 terminal=last*(1+g)*.35*(1-c['tax'])*(1-g/roic)/(w-g)/(1+w)**5
 at2030=transition_pv+terminal
 from src.model import bridge
 b=bridge(data,c);ev=r['cases']['base']['explicit_pv']+at2030/(1+w)**(c['remaining_days']/365+4)
 transition_price=(ev+b.cash+b.investments-b.debt-b.other_claims)/b.shares
 stresses.append(dict(scenario='Maturity deferred to2035 with five-year fade',value=transition_price,current_action='do_not_initiate' if c['price']>1.2*transition_price else 'watch_defer',conditional_price=20,conditional_action='initiate_candidate' if 20<.8*transition_price else 'watch_defer'))
 dump_csv('outputs/named_stresses.csv',stresses)
 low=r['cases']['low']['per_share'];high=r['cases']['high']['per_share'];bv=r['cases']['base']['per_share']
 memo=f'''# Palantir independent committee memo — provisional
Created {datetime.now(timezone.utc).isoformat()}. AI-generated after the official checkpoint; not official EditionA or Pierce's original judgment.

Conditional action: **do not initiate at the October5,2026 regular close of $189.40 under this evidence and model.** Fundamental DCF case range is approximately **${low:.0f}–${high:.0f} per diluted economic share**, with base around ${bv:.0f}. This is a judgment-dependent interval, not a statistical confidence interval or a universal price ceiling. Senior analysts retain sector strategy; Pierce must review the material assumptions. Course and human validations remain pending.

The fund has no position. Intended user: buy-side analyst group and portfolio manager. Decision horizon:3–5 years. Security: NASDAQ PLTR ClassA; USD; count ClassA/B/F economic ownership, distinguish point-in-time basic from weighted-average EPS shares. Palantir sells software and services with identifiable operating revenue, costs, working capital and reinvestment; operating-company enterprise FCFF is appropriate. It is not a regulated financial intermediary or property trust. No trading execution or public publishing is authorized by this analysis.

## Evidence and accounting
2025 annual10K published February17,2026 supplies the audited base. June30,2026 10Q published August4 supplies separate interim statements and the bridge. October5 close is the valuation/information cutoff; October6 quotes are excluded. Cash and awards remain latest reported June30 amounts, not claims of an October5 balance. Management's August3 guidance midpoint is a forecast input, not realized revenue. Every raw source and its failures are in the source manifest; peer snapshots have reproducible primary URLs when bulk downloads were blocked.

Retain ongoing stock-compensation costs through cash-replacement economics; explicitly dilute existing awards and remove their remaining service expense before future replacement costs. Full award vesting and SAR full-share treatment are conservative approximations, not option pricing. Exclude restricted cash from distributable equity credit. Normalize operating cash taxes to25%; remove non-operating interest/investment income from FCFF. Operating lease expense remains within EBIT, so lease liabilities are not arbitrarily treated as financial debt. No hidden funding plug: cash is generated by the cash-flow roll-forward and an explicit deficit would fail.

## Cases and expectations
Low: commercial conversion slows, government procurement delays, margins compress and collections absorb cash. Base: strong commercial adoption decelerates; government growth moderates; margin fades toward maturity. High: repeatable deployment extends strong adoption and efficient cash collection. Terminal PV accounts for about {r['cases']['low']['terminal_share']:.0%}–{r['cases']['high']['terminal_share']:.0%} of EV. The high case is especially maturity-dependent. Five-year immediate maturity is a major assumption: delaying maturity to2035 in a separate terminal fade produces roughly ${transition_price:.0f}; it still does not support the observed price in this specification.

Base WACC10.56%=Treasury10-year5.31% on October5 + assumed operating beta1.25 times October1 implied ERP4.20%. The beta is analyst judgment, not a completed regression. WACC8–13% sensitivity is reported; no borrowed precision from a provider beta. Terminal growth2–4%, terminal margins30–40%, mature ROIC25%; reinvestment is explicitly growth/ROIC. The terminal convention can still understate intangible reinvestment and competitive fade.

Reverse DCF holds base margins, government growth, tax, WACC and maturity fixed and scales commercial growth until price matches. It implies commercial growth of approximately {', '.join(f'{x:.0%}' for x in r['reverse_dcf']['annual_growths'])} over2027–30. This isolates one burden of expectations; it is not the only combination consistent with market price. A longer competitive-growth runway or different risk/terminal assumptions could redistribute that burden.

## Relative valuation and disagreement
Policy was recorded before name selection. NOW provides a workflow/platform comparison; CRM provides a mature enterprise-application comparison. Their latest TTM periods end June30 and July31; that one-month fiscal-calendar mismatch is exposed rather than presented as identical. All prices use October5 regular close and all numerators use point-in-time basic share counts. Balances and shares precede prices. EV/revenue uses debt less cash and marketable securities; operating leases stay in operating costs. Strategic equity portfolios receive no separate credit consistently, which is conservative and economically imperfect. GAAP P/E includes investment gains and discrete tax effects; it is a qualified comparison.

Peer EV/revenue implies roughly $17–$28 per basic PLTR share. Peer GAAP P/E implies roughly $25–$106. Do not average these or splice basic-share relative results into diluted DCF values. Revenue multiples suppress differences in growth and economic margin. P/E can reward unusually low taxes and investment gains; CRM's investment gains and NOW's tax release make earnings denominators poor clean operating anchors. DCF explicitly prices fade, compensation and reinvestment; relative methods reflect what buyers currently pay for different companies. Disagreement is evidence about assumptions and accounting, not a reason to average numbers.

No transaction multiple is forced into the analysis: control, synergy, integration and timing differences lack a defensible PLTR bridge.

## Conditions, reversals and monitoring
Revisit after reported commercial/government sales and collection evidence, not options-inclusive deal value alone. Require funded commitments and realizable conversion; distinguish RPO from cancellable RDV/TCV. Monitor GAAP margin, ongoing compensation payroll, award issuance, cash taxes, hosting commitments, capex, receivable concentration and competitive pricing. Two consecutive quarters of realized adoption above the high-case path warrant a rebuilt runway/maturity model rather than mechanically moving a single multiple. A materially lower market price or independently evidenced longer profitable runway can reverse the decision. Under a hypothetical future $20 price, base economics support an initiate candidate while the conversion/procurement downside reverses that action; this is a conditional downside, not a forecast of a price decline.

## Validation limits and human work
Arithmetic and boundary tests pass; this is not proof of sound investment judgment. Published starter reconciliation, genuine locked prediction/test, attributed partner challenges, actual recordings/transcripts, official rubric/checklist and comparison with Pierce's existing work remain pending. Independent research has not been substituted for the official EditionA receipt. No complete course-compliant submission is claimed.
'''
 save('submission/independent-memo.md',memo)
 fragments=['<h1>Palantir — independent finance review</h1>',f'<p>Valuation date October5,2026 | Provisional DCF range ${low:.0f}–${high:.0f} | Conditional action: do not initiate at $189.40</p>','<p>All currency and shares in millions; DCF values diluted, peer-relative values basic. Required course and human gates pending.</p>']
 import pandas as pd
 for title,file in [('Case results','results.json'),('Five-year base integrated forecast','base_three_statements.csv'),('WACC–growth sensitivity','wacc_growth.csv'),('Comparables','peer_multiples.csv'),('Relative valuation','relative_valuation.csv'),('Named stresses','named_stresses.csv')]:
  fragments.append('<h2>'+title+'</h2>')
  if file.endswith('.csv'):fragments.append(pd.read_csv('outputs/'+file).round(3).to_html(index=False))
  else:fragments.append('<pre>'+html.escape(json.dumps(r,indent=2))+'</pre>')
 fragments.append('<h2>Committee memo</h2><pre>'+html.escape(memo)+'</pre>')
 save('outputs/review.html','<!doctype html><meta charset="utf-8"><title>Palantir finance review</title><style>body{font:16px system-ui;margin:40px;color:#1b2735}table{border-collapse:collapse;font-size:13px;display:block;overflow:auto}td,th{padding:7px;border:1px solid #ccd3dc}pre{white-space:pre-wrap;line-height:1.5}h2{margin-top:35px}</style>'+''.join(fragments))
 save('README.md','''# Palantir corporate finance — FIN439
Private independent project for Pierce Appleton. Official EditionA is unchanged and uninspected. This is an AI-generated postcheckpoint analysis with pending course/human gates.

## Visible results
[Committee memo](submission/independent-memo.md), [static review](outputs/review.html), [case and reverse DCF results](outputs/results.json), [base five-year statements](outputs/base_three_statements.csv), [sensitivity](outputs/wacc_growth.csv), [peer multiples](outputs/peer_multiples.csv), [named stresses](outputs/named_stresses.csv). DCF range approximately$16–$66; conditional do-not-initiate at October5 close$189.40. See assumptions and limitations before accepting this provisional decision.

## Setup and reproduction
Python3.14.7 was used. From repository root:
```
python -m venv .venv
.venv\\Scripts\\python.exe -m pip install -r requirements.txt
.venv\\Scripts\\python.exe -m src.reproduce
.venv\\Scripts\\python.exe -m streamlit run app/main.py
```
The reproduction command uses saved historical evidence/inputs; it does not require live prices or blocked SEC downloads. Raw retrieval scripts record actual403 failures; Palantir issuer mirrors are saved with hashes. Peer and market inputs include primary/retrieval URLs and as-of dates. No credentials are committed.

## Navigation and validation
Read PROJECT_GUIDE.md, docs/STATUS.md, docs/requirements-matrix.csv, docs/normalization.md, docs/assumption-challenges.csv, docs/source_manifest.json and validation/STATUS.md. Financial engine is in src; interface is in app. Designated locked capex change remains unexecuted pending actual human prediction/precommit. Published training-case answers, partner feedback and recordings are not invented.

Official submission grouping/filenames,300-point rubric and limits await supplied course materials; current submission filenames are working artifacts, not claimed official names.
''')
if __name__=='__main__':run()